### PR TITLE
New subtitle support

### LINKED ISSUE #48: Subtitles are not displayed in Paella Player 7 when using mod, filter or repository plugin
The new way of supporting subtitles in Opencast 15 must be provided when extracting captions.

Please see https://github.com/Opencast-Moodle/moodle-block_opencast/issues/367 for more info!

### PR DESCRIPTION
**Pull request by ferishili**
This PR fixes #48 

### Description
In Opencast 15, captions (subtitles) are provided with different format as for their flavors: captions/delivery ... etc. and every other data including language code etc. is included in the tags.

### Solution
- This patch covers the new subtitles format while it maintain the old ones.
- The get_caption function now cover attachments and media and for media also looks for old and new subtitles.

### To TEST
- You would need to have Opencast 15.
- You would need to have auto generated captions as well as manually uploaded caption via block_opencast plugin (or any other way) in order to test all cases.
- Try to watch the event via this plugin or in filter plugin
- All captions must be accessible in the paella player!

### CODE REVIEW

**Comment by mwuttke** [comment]
Hello @ferishili, 
I tested videos with subtitles created by amberscript in english & in german with in the mod plugin, embedded in a page and embedded in a book page. And I tested videos with subtitles created by whisper and by whipsercpp in english & in german with in the mod plugin, embedded in a page and in a book page. I all scenarios the subtitles where shown.
So the patch works for me. ;-)

**Comment by mwuttke** [comment]
@NinaHerrmann & @justusdieckmann, what do you think speaks against reviewing and releasing this PR?

**Comment by NinaHerrmann** [comment]
We do not have the capacity to review it.

**Review by justusdieckmann — COMMENTED** [review]
Hey @ferishili,

thank you very much for the pull request! 

If I understand correctly, in all cases where the `strpos` is checked, the search-string should be at the start of the full string, right? So maybe `strpos(...) === 0` would be better in those cases.   Also, instead of `str_replace('prefix', '', $tag)`, maybe you could use `substr($tag, strlen('prefix'))`, because that will also work correctly in the (very unlikely) case, that 'prefix' is contained later in the string again.

Do you have any pointers to workflows or documentation regarding how to best setup the automatic captions to have an video to test with? I have found a talk about it, and the `ts-api` repo, but no instructions how to integrate it in opencast.

Thank you!
Justus

**Comment by ferishili** [comment]
Hi @justusdieckmann,
The changes are applied. 

Unfortunately, I have very little knowledge about automatic captions, but I would guess these docs could help!

https://docs.opencast.org/r/15.x/admin/#configuration/transcription.configuration/whisper/
https://docs.opencast.org/r/15.x/admin/#configuration/transcription.configuration/vosk/

**Pull request merged**
