### PR TITLE
Fix: null value for array_key_first

### LINKED ISSUE #43: Fehler beim Aufruf einer Opencast Aktivität
Bei unserem Moodle (4.1) mit mod_opencast (v4.3-r1) bekommen wir bei manchen Videos den folgenden Fehler:
Bildschirmfoto 2024-02-21 um 09 47 42

In anderen Kursen wiederum funktioniert es einwandfrei.

### PR DESCRIPTION
**Pull request by ferishili**
This PR fixes #43

### CODE REVIEW

**Comment by ferishili** [comment]
Hi @slaudel
That would be great if you could test this PR and write your feedback here.
I am just wondering, what happen in that course if there is no `sources` in the `streams`

**Comment by NinaHerrmann** [comment]
In case of `empty($data['streams'][0]['sources'])` shouldn't we rather display a more meaningful message? Because it is not possible to display a video without source right?

**Comment by NinaHerrmann** [comment]
That would be beautiful, thank you! :)

**Comment by ferishili** [comment]
Hi @NinaHerrmann,
I've added the notification, please take a look and adjust the text.
Thanks in advance

**Comment by NinaHerrmann** [comment]
Thank you so much @ferishili, looks good to me!

**Pull request merged**
