### PR TITLE
Fix error notification

### PR DESCRIPTION
**Pull request by geichelberger**
The error notification is shown if two or more streams are available, but it should only be displayed if there are no streams.

### CODE REVIEW

**Review by ferishili — APPROVED** [review]
I have first rebased this PR and added some minor improvements. Hence, I would say, it is good to go!

**Comment by geichelberger** [comment]
Did you rebase it or merge a branch into that one because of a merge commit? What's the improvement? Because the error notification is now removed.

**Comment by ferishili** [comment]
> Did you rebase it or merge a branch into that one because of a merge commit? What's the improvement? Because the error notification is now removed.

Yes, I wrote that I rebase and merged. The part to handle that was merged, before via: https://github.com/Opencast-Moodle/moodle-mod_opencast/commit/f48a850b14840e2b08717e0cc8b57bfd51522c1d

**Comment by geichelberger** [comment]
So basically, a duplicate of that PR got merged before this one, which was created almost 3 months later.

**Comment by ferishili** [comment]
Unfortunately, it does seem that way. It looks like this PR might have been impacted by changes in personnel and limited time for repository management when it was originally created. Apologies for any inconvenience, and thank you for your understanding.

**Pull request merged**
